export enum AuditAction {
  CREDENTIAL_ISSUED = 'CREDENTIAL_ISSUED',
  CREDENTIAL_ISSUE_FAILED = 'CREDENTIAL_ISSUE_FAILED',
  CREDENTIAL_REVOKED = 'CREDENTIAL_REVOKED',
  CREDENTIAL_REISSUED = 'CREDENTIAL_REISSUED',
  STUDENT_RECORD_ERASED = 'STUDENT_RECORD_ERASED',
  USER_CREATED = 'USER_CREATED',
  USER_LOGIN = 'USER_LOGIN',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  STATUS_LIST_PUBLISHED = 'STATUS_LIST_PUBLISHED',
}
